@HotelManagement.API_HostAddress = http://localhost:5160

GET {{HotelManagement.API_HostAddress}}/weatherforecast/
Accept: application/json


###
GET {{HotelManagement.API_HostAddress}}/api/cliente/
Accept: application/json

###

POST {{HotelManagement.API_HostAddress}}/api/cliente/
Content-Type: application/json

{
    "nombre": "Jonathan",
    "apellido": "Miskinich",
    "telefono": "1150354498",
    "email": "jonathan@gmail.com",
    "dni": 460157
}

###

PUT {{HotelManagement.API_HostAddress}}/api/cliente/5
Content-Type: application/json

{
    "id": 5,
    "isDeleted": false,
    "NOMBRE": "Jonathan",
    "APELLIDO": "Miskinich",
    "telefono": "1150354498",
    "EMAIL": "jonathan@gmail.com",
    "DNI": 460157
}

###

DELETE {{HotelManagement.API_HostAddress}}/api/cliente/5

###
GET {{HotelManagement.API_HostAddress}}/api/reserva/
Accept: application/json

###

GET {{HotelManagement.API_HostAddress}}/api/reserva/obtenerporcliente/1
Accept: application/json

### 

POST {{HotelManagement.API_HostAddress}}/api/reserva/
Content-Type: application/json

{
    "FechaInicio": "2023-01-01",
    "FechaFin": "2024-02-05",
    "IdCliente": 1,
    "IdHabitacion": 1,
    "IdEstadoReserva": 1
}

###

PUT {{HotelManagement.API_HostAddress}}/api/reserva/cancelar/1
Content-Type: application/json

{
    "FechaInicio": "2023-01-01",
    "FechaFin": "2024-02-05",
    "IdHabitacion": 1,
    "IdEstadoReserva": 3
}

###

PUT {{HotelManagement.API_HostAddress}}/api/reserva/1
Content-Type: application/json

{
    "Id": 1,
    "FechaInicio": "2023-01-01",
    "FechaFin": "2024-02-05",
    "IdHabitacion": 1,
    "IdEstadoReserva": 1
}

###

DELETE {{HotelManagement.API_HostAddress}}/api/reserva/1    

